### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by wadewegner** [BrianDGLS/express-ts#2]
Thanks for the sample.

When I run this ...
```
❯ node build/server.js
Listening at http://localhost:3000/
```
... I get `Cannot GET /`.

**Comment by fyn-dev** [comment]
Have a look in the source code. You should use http://localhost:3000/welcome

**Comment by BrianDGLS** [comment]
@wadewegner does the above comment fix your issue?

**Comment by BrianDGLS** [comment]
Closing as no response.
