### ISSUE TITLE
Cannot invoke an expression whose type lacks a call signature. Type 'never' has no compatible call signatures.

### ISSUE THREAD

**Issue by abhijagtap73** [BrianDGLS/express-ts#4]
![image](https://user-images.githubusercontent.com/11439561/43700511-7c6d3600-9970-11e8-89cc-fbef9a70fb73.png)

I am getting this error after  Typescript compile.

**Comment by BrianDGLS** [comment]
Thanks, I'll update the article soon. Types like this seem to change alot. I'll investigate and update it to use the correct type.

**Comment by pdtyreus** [comment]
I was able to resolve this by changing the way `express` was imported

```ts
import express from 'express';
```

**Comment by BrianDGLS** [comment]
Seems like a good solution to me.

Do you want to create a PR for that @pdtyreus ?

If not I'll update it soon.

**Comment by BrianDGLS** [comment]
Updated, closing issue.

Thanks @pdtyreus  and @abhijagtap73
