### ISSUE TITLE
error: Type 'string | 3000' is not assignable to type 'number'

### ISSUE THREAD

**Issue by mattdamon108** [BrianDGLS/express-ts#5]
Hi, Brian. Thank you for your wonderful tutorial. It helps me a lot to look into typescript & express.

I'd like to ask how to solve an error I encountered. I followed your tutorial and input exactly same codes, but I have an error.

```
app/server.ts:6:7 - error TS2322: Type 'string | 3000' is not assignable to type 'number'.
  Type 'string' is not assignable to type 'number'.
```
Simply, if I remove `process.env.PORT`, error is solved. But I'm wondering how to resolve with this code.

**Comment by mattdamon108** [comment]
Actuall, I found a some way to resolve this problem and pull request it. Please check the pull request.

**Comment by BrianDGLS** [comment]
@mattdamon108 , merged your PR. Thanks.
